version: "3.7"

services:
watchtower:
    container_name: watchtower
    hostname: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 24 # default is 24 hours, change this to your liking: recommdation is 30 seconds
